import type { Metadata } from "next";
import "./globals.css";
import { Crimson_Text, Playfair_Display } from "next/font/google";

export const crimsonText = Crimson_Text({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
